services:
  beta_psql_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - beta_psql_volume:/var/lib/postgresql/beta_data

  beta_goapp:
    build: .
    depends_on: 
      - beta_psql_db
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      FRONTENDPORT: ${FRONTENDPORT}

      IS_PROD: ${IS_PROD}
      PROD_HOST: ${PROD_HOST}

      JWT_SIGN_SECRET: ${JWT_SIGN_SECRET}
      AUTH_KEY_SECRET: ${AUTH_KEY_SECRET}
      DB_ENCRYPT_KEY_SECRET: ${DB_ENCRYPT_KEY_SECRET}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    command: >
      sh -c "./goose_migrate.sh && ./main"

volumes:
  beta_psql_volume: