// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type User struct {
	ID        int32
	UserID    string
	Email     string
	FirstName sql.NullString
	LastName  sql.NullString
	BirthDate sql.NullTime
	Gender    sql.NullString
	Avatar    sql.NullString
	Location  sql.NullString
	Interests sql.NullString
	CreatedAt sql.NullTime
}
