// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int32
	UserID    string
	Email     string
	FirstName sql.NullString
	LastName  sql.NullString
	BirthDate sql.NullString
	Gender    sql.NullString
	Location  sql.NullString
	Interests sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserAvatar struct {
	ID     int32
	UserID string
	Avatar sql.NullString
}
