// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, email)
VALUES ($1, $2)
RETURNING id, user_id, email, first_name, last_name, birth_date, gender, location, interests, created_at
`

type CreateUserParams struct {
	UserID sql.NullInt32
	Email  sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.UserID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.Location,
		&i.Interests,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, user_id, email, first_name, last_name, birth_date, gender, location, interests, created_at FROM users
WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID sql.NullInt32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.Location,
		&i.Interests,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET first_name = $2, last_name = $3, birth_date = $4, gender = $5, "location" = $6, interests = $7
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID    sql.NullInt32
	FirstName sql.NullString
	LastName  sql.NullString
	BirthDate sql.NullTime
	Gender    sql.NullString
	Location  sql.NullString
	Interests sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.Location,
		arg.Interests,
	)
	return err
}
