name: Deploy Beta

on: 
  push: 
    branches: [ beta-deploy ]

jobs: 
  build:
    runs-on: ubuntu-latest
    environment: beta

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Get Variables
            USER=${{ secrets.USERNAME }}
            
            # Pull repo source
            cd /home/${USER}/deployment_repos/coop/src
            git checkout beta-deploy
            git pull origin beta-deploy

            # Export Env Vars
            # BACKEND
            export IS_PROD=true
            export PROD_HOST=${{ secrets.PROD_HOST }}
            export BACKEND_PORT=${{ secrets.BACKEND_PORT }}
            export FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
            export JWT_SIGN_SECRET=${{ secrets.JWT_SIGN_SECRET }}
            export AUTH_KEY_SECRET=${{ secrets.AUTH_KEY_SECRET }}
            export DB_ENCRYPT_KEY_SECRET=${{ secrets.DB_ENCRYPT_KEY_SECRET }}
            export EXTERNAL_DB_PORT=${{ secrets.EXTERNAL_DB_PORT }}
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_PORT=${{ secrets.DB_PORT }}
            export DB_DATABASE=${{ secrets.DB_DATABASE }}
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}

            # FRONTEND
            export REACT_APP_IS_PROD=true
            export REACT_APP_API_PROD_HOST=${{ secrets.REACT_APP_API_PROD_HOST }}
            export REACT_APP_API_PORT=${{ secrets.REACT_APP_API_PORT }}

            # Run all as docker orchestration (db, backend, frontend, proxy)
            docker compose build
            docker compose up -d --remove-orphans