name: Deploy Beta

on: 
  push: 
    branches: [ beta-deploy ]

jobs: 
  build:
    runs-on: ubuntu-latest
    environment: beta

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Get Variables
            USER=${{ secrets.USERNAME }}
            
            # Pull repo source
            cd /home/${USER}/deployment_repos/coop/src
            git checkout beta-deploy
            git pull origin beta-deploy

            # Change to Backend Dir and Export Env Vars
            cd backend
            export IS_PROD=true
            export PROD_HOST=${{ secrets.PROD_HOST }}
            export PORT=${{ secrets.PORT }}
            export FRONTENDPORT=${{ secrets.FRONTENDPORT }}
            export JWT_SIGN_SECRET=${{ secrets.JWT_SIGN_SECRET }}
            export AUTH_KEY_SECRET=${{ secrets.AUTH_KEY_SECRET }}
            export DB_ENCRYPT_KEY_SECRET=${{ secrets.DB_ENCRYPT_KEY_SECRET }}
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_PORT=${{ secrets.DB_PORT }}
            export DB_DATABASE=${{ secrets.DB_DATABASE }}
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            
            # Run backend as a docker orchestration (2 containers -- app and db)
            docker compose build
            docker compose up -d

            # Change to Frontend Dir and Export Env Vars
            cd ../frontend
            export REACT_APP_IS_PROD=true
            export REACT_APP_API_PROD_HOST=${{ secrets.REACT_APP_API_PROD_HOST }}
            export REACT_APP_API_PORT=${{ secrets.REACT_APP_API_PORT }}

            # Define the node package manager bin we should use
            export NPM_BIN=/home/${USER}/.nvm/versions/node/v21.6.1/bin/npm

            # Install node modules if not present
            if [ ! -d "node_modules" ]; then
              $NPM_BIN install
            fi
            
            # Build frontend 
            $NPM_BIN run build

            # Move frontend build to nginx serve location
            rm -rf /var/www/beta.coop.casa/*
            mv build/* /var/www/beta.coop.casa/
            cd ..