name: Deploy

on: 
  push: 
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Get Variables
            USER=${{ secrets.USERNAME }}
            
            # Pull repo source
            cd /root/deployment_repos/coop/src
            git pull origin main

            # Change to Backend Dir and Export Env Vars
            cd backend
            export IS_PROD=true
            export PROD_HOST=${{ secrets.PROD_HOST }}
            export PORT=${{ secrets.BACKEND_API_PORT }}
            export FRONTENDPORT=${{ secrets.FRONTENDPORT }}
            export JWT_SIGN_SECRET=${{ secrets.JWT_SIGN_SECRET }}
            export AUTH_KEY_SECRET=${{ secrets.AUTH_KEY_SECRET }}
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_PORT=${{ secrets.DB_PORT }}
            export DB_DATABASE=${{ secrets.DATABASE }}
            export DB_USERNAME=${{ secrets.USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            
            # Build backend
            make build

            # Run backend in tmux session
            SESSION_NAME="coop"
            DIRECTORY="/home/${USER}/deployment_repos/coop/src/backend"
            COMMAND="/home/${USER}/deployment_repos/coop/src/backend/main"

            # Check if the tmux session exists
            tmux has-session -t $SESSION_NAME 2>/dev/null

            if [ $? != 0 ]; then
                echo "Session $SESSION_NAME does not exist, creating it"
                tmux new-session -d -s $SESSION_NAME "$COMMAND"
            else
                echo "Session $SESSION_NAME exists, killing and creating a new one"
                tmux kill-session -t $SESSION_NAME
                tmux new-session -d -s $SESSION_NAME "$COMMAND"
            fi

            # Change to Frontend Dir and Export Env Vars
            cd frontend
            export REACT_APP_IS_PROD=true
            export REACT_APP_API_PROD_HOST=${{ secrets.REACT_APP_PROD_HOST }}
            export REACT_APP_API_PORT=${{ secrets.REACT_APP_API_PORT }}
            
            # Build frontend 
            /home/${USER}/.nvm/versions/node/v21.6.1/bin/npm run build

            # Move frontend build to nginx serve location
            rm -rf /var/www/coop/*
            mv build/* /var/www/coop/
            cd ..