name: Deploy

on: 
  push: 
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/deployment_repos/coop/src
            git pull origin main
            ./build_and_run_prod.sh